## JOYOUS CONFIG
## * 配置存在错误或不存在会视作默认值，但不推荐这么做
## 注释中[$?]表示填写的值

## SMenu 模块
# 提供双端通用菜单和在线编辑器：
# 在线编辑菜单：https://mc.kdxiaoyi.top/Joyous-MenuEditor/
SMenu:
  ## 是否启用
  # * 不支持热重载
  enabled: true
  ## 菜单物品设置
  menu-item:
    ## 显示的图标
    # Minecraft标准物品名，不含命名空间
    material: "clock"
    ## 特化
    # 启用后只有插件给予的菜单才能使用
    # 同时只要物品有插件的特殊数据就能打开菜单
    specialized: true
    ## 显示
    # 至少1行。首行为物品名，其它为描述
    display:
      - &b菜单
      - &7Powered by StreackMC/Joyous.
      - 每行开头无需手动重置样式，会自动重置。这行文本就不是斜体嫣紫的。
    ## 给予
    # 进入服务器时背包没有菜单是否要给一个新的
    # ！禁用后你需要手动处理菜单给予，要不然就需要开放命令 /smenu open 或者 /smenu get 。
    give: false
  ## 命令别名
  # 默认命令为 /smenu
  alias: []
  ## 冷却
  # 玩家需要间隔多久才能再次打开菜单。使用 /smenu open [menu] 指定菜单可以绕过。
  cooldown: 3
  ## 缓存时长
  # 一个菜单被访问以后会在接下来的 $? 秒内被持续加载，这可以提升高访问量的菜单的响应速度，减少 IO 开销；
  # 本功能的内存开销几乎可以忽略（相较整个服务器而言）；
  # 但需要注意缓存有效期内菜单文件不会自动重载，需要手动使用命令 /smenu reload 可以立即删除全部缓存；
  # PHAPI（若有）仍是在打开菜单时解析的
  cahce_ttl: 1800

## APIHolders 模块
# 用于提供在线查询API
APIHolders:
  ## 是否启用
  # 需要 StreackLib 中启用 HTTPServer
  # * 不支持热重载
  enabled: true
  ## 监听路径
  # 必须以 / 开头，ph查询特定Placeholder，status查询服务器状态。
  # * 留空表示不启用
  # * 不支持热重载
  path:
    ph: "/api/placeholder"
    status: "/api/status"
  ## 跨域请求（CORS）标头
  # 在前端应用中，浏览器会限制跨域请求，即只允许下面配置的域名和同域名获取数据。
  # 这个设置具体控制Access-Control-Allow-Origin标头的内容，它可以为：
  # 1. "*"：允许所有域名；
  # 2. "null"：只允许同域名（此用法已被MDN不推荐使用）；
  # 3. 单个具体域名，例如 "https://example.com"：只允许该域名获取数据。
  cors-allowed: "*"
  ## 缓存时长
  # 对于 StatusAPI ，连续两次刷新数据需要间隔的时间。单位：秒
  cache: 60
  ## 名单模式
  # 启用即白名单，只允许查询匹配的；否则为黑名单，允许查询全部不匹配的（不推荐）
  white-mode: true
  ## 限制查询的 Placeholders 名单列表
  # 无需携带「%」，支持两种写法：
  # 1. 普通字符串，全匹配（忽略大小写）
  # 2. "regex:正则表达式"  正则匹配
  ph_list:
    - "player_name"
    - "server_online"
    - "regex:server_.*"
  ## 是否允许模糊查询 Placeholders
  # 启用后，允许通过使用 text 参数进行查询
  # 不保证上述过滤机制可以正常工作。故不推荐启用
  # 这个参数传入的文本会直接作为一整段「文本」进行处理，而非「Placeholder」
  allow_blurred_ph: false

## Entroprix（熵流） 模块
# 随机抽卡系统，允许定义 保底 多金 up 等数据
# 相较于数据包的战利品表而言更简洁易用
# 参见 entroprix.yml
Entroprix:
  ## 是否启用
  # * 不支持热重载
  enabled: true
  ## 最大连续抽取次数
  # 用于限制 roll 子命令中的最大次数，原版上限为 65535
  # 同时抽取次数过大会导致服务器严重卡顿（抽卡主要开销来自执行命令）
  # * 无论如何设置，都不能超过 1000
  # * 设为比1小的值会导致无法抽卡
  max: 100
  ## 命令别名
  # 默认命令为 /entroprix
  alias:
    - "gacha"

## PlayerTitle 模块
# 一个十分轻量、轻量过头的玩家称号系统，基本原理是提供一个 Placeholder ，传入时判断玩家偏好来返回对应称号，并通过权限来控制是否拥有所有权。
# 参见 models/playerTitles.yml 来添加称号
PlayerTitle:
  ## 是否启用
  # * 不支持热重载
  enabled: true
  ## 称号前缀
  prefix: "&7「"
  ## 称号后缀
  suffix: "&7」&r"
  ## 命令别名
  # 默认命令为 /playertitle
  alias:
    - "ptitle"

## Mails 模块
Mails:
  ## 是否启用
  # * 不支持热重载
  enabled: true

## Restarter 模块
# 本模块的基本用法是
# /jrestart [秒数] [理由] - 计划重启并全服通知
# /jstop [秒数] [理由] - 计划关闭并全服通知
# 不过另请注意，重启相关功能需要正确配置服务器侧 Restart 功能
# 在 /spigot.yml 的 settings.restart-script 处设置脚本路径
# 并确保脚本有执行权限，本功能才可正常使用，否则只会关闭而不重启
# 此外可能还有其他问题也会导致不生效，请自行判断
# 为提供开发能力，重启时服务器控制台会输出一行类似 [Joyous] →​J​o​y​o​u​s​← 的日志，其中箭头中间的每个字母的两边都有一个 \u200b 字符，共计7个。
Restarter:
  ## 是否启用
  # * 不支持热重载
  enabled: true
  ## 在服务器意外关闭后计划重启
  # 启用后只能使用 /jstop 安全关闭服务器
  preventInterrupt: false
  ## 是否要展示顶部倒计时条
  showBossbar: true
  ## 在没有输入秒数时的默认值
  defaultTimeout: 60
  ## 配置自动重启
  autoRestart:
    ## 自动重启时的倒计时（秒）
    # 等于0立即重启，小于0禁用本功能
    timeout: -1
    ## 触发时间条件
    when:
      ## 在当天的什么时候计划重启
      # 计划后会经过上面的 timeout 倒计时秒
      hour: 12
      min: 00
      sec: 00
      ## 每周?
      # 支持混排，示例为星期一、四、六
      weekday: 164
      ## ?月?日
      days:
        - 7.2
        - 2.30 # 非法值会被忽略
      ## 每月的特定日
      dayOfM:
        - 1 # 1日
        - ?5 # 5、15、25日
        - 1? #10...19日
    ## 触发其它条件
    while:
      # 当堆内存达到上限的百分之多少，小于等于 0 禁用
      # 堆内存上限指的是 -Xmx 设置的数值
      # 值得一提，StatusAPI 提供的内存信息还计入了非堆内存
      oomPercent: 80
    ## 重启后保留假人的兼容性配置
    # 本功能只要启动都会自动生效，无论由于什么而启动
    fp:
      # 功能开关
      enabled: true
      ## 怎么找到假人
      identify:
        # 拥有如下权限
        perm: 'streack.fakeplayer'
        # 启用后假人可以被命令 /jrestarter fp <add/remove> <player> 添加
        command: true
      # 生成假人的命令
      # 此处以及后者的命令无需携带 / ，使用 %name% 插入假人名称
      spawn: 'fp spawn %name%'
      # 使假人登录的命令
      login: 'authme forcelogin %name%'
      # login 在玩家加入后执行的延迟毫秒
      delayOfJoin: 2000

## 配置文件版本
version: 000204
# 如无必要请勿修改