name: Joyous
version: ${project.version}
author: "StreackMC Team"
description: ${project.description}
website: https://github.com/StreackMC/Joyous
api-version: '1.14'
main: com.github.streackmc.Joyous.entry
depend: ["StreackLib", "PlaceholderAPI"]

commands:
  apiholders:
    description: "管理 APIHolders 模块"
    usage: "/<command> <version|reload>"
    permission: joyous.apiholders.command

permissions:
  joyous.apiholders.command:
    description: "允许使用 /apiholders 管理 APIHolders 模块"
    default: op