name: Joyous
version: ${project.version}
author: "StreackMC Team"
description: ${project.description}
website: https://github.com/StreackMC/Joyous
api-version: '1.20.6'
main: com.github.streackmc.Joyous.entry
depend: ["StreackLib", "PlaceholderAPI"]