name: Joyous
version: ${project.version}
author: "StreackMC Team"
description: ${project.description}
website: https://github.com/StreackMC/Joyous
api-version: '1.14'
main: com.github.streackmc.Joyous.entry
depend: ["StreackLib", "PlaceholderAPI"]

commands:
  joyous:
    description: "未使用的命令"
    usage: "/<command>"
    permission: joyous.unused

permissions:
  joyous.unused:
    description: "根权限，目前未使用"
    default: op